
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JiTU-PC
 */
public class forget extends javax.swing.JFrame {

    /**
     * Creates new form forget
     */
    public forget() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        d1 = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jdob = new javax.swing.JLabel();
        jpwd = new javax.swing.JLabel();
        jadm = new javax.swing.JLabel();
        tadm = new javax.swing.JTextField();
        tdob = new javax.swing.JTextField();
        tpwd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        d1.setUndecorated(true);
        d1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Utsaah", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" succesfully chaned");
        d1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 130, 30));

        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 1, true));
        d1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 223, 114));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdob.setText("Date of Birth");
        jdob.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jdob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdobMouseClicked(evt);
            }
        });
        getContentPane().add(jdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 120, 20));

        jpwd.setText("New Password");
        jpwd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpwdMouseClicked(evt);
            }
        });
        getContentPane().add(jpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 120, 20));

        jadm.setText("Admision No.");
        jadm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jadm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jadmMouseClicked(evt);
            }
        });
        getContentPane().add(jadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 120, 20));

        tadm.setBorder(null);
        getContentPane().add(tadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 130, -1));

        tdob.setBorder(null);
        getContentPane().add(tdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 130, -1));

        tpwd.setBorder(null);
        getContentPane().add(tpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 130, -1));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 110, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/iconfinder_arrow-right_227601.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/reset.jpg"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 354, -1));

        setSize(new java.awt.Dimension(354, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jadmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadmMouseClicked
        jadm.setVisible(false);
        
    }//GEN-LAST:event_jadmMouseClicked

    private void jdobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdobMouseClicked
jdob.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jdobMouseClicked

    private void jpwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpwdMouseClicked
jpwd.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jpwdMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try{
        Class.forName("java.sql.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://remotemysql.com:3306/PwgAV9gxe3","PwgAV9gxe3","CjiamOUePn");
        Statement stmt=con.createStatement();
        int s1=Integer.parseInt(tadm.getText());
   
        String s2=tdob.getText();
        String s3=tpwd.getText();
        String q="select*from sdetail where admno="+s1+"";
        ResultSet rs=stmt.executeQuery(q);  
       
        rs.next();
        String s4=rs.getString("dob");
        if(s2.equals(s4)){
          stmt.executeUpdate("update sdetail set password='"+s3+"' where admno="+s1+";");
          d1.setVisible(true);
           //JOptionPane.showMessageDialog(null,"Password Changed succesfully"); 
        }
        else{
            JOptionPane.showMessageDialog(null,"Incorrect details");
           //d1.setVisible(true);
        }
        
       
      
        stmt.close();
        con.close();                      
}
catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            }  
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new newlogin().setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog d1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jadm;
    private javax.swing.JLabel jdob;
    private javax.swing.JLabel jpwd;
    private javax.swing.JTextField tadm;
    private javax.swing.JTextField tdob;
    private javax.swing.JTextField tpwd;
    // End of variables declaration//GEN-END:variables
}
