import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JiTU-PC
 */
public class newlogin extends javax.swing.JFrame {

    /**
     * Creates new form newlogin
     */
    public newlogin() {
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_print = new javax.swing.JPanel();
        lg = new javax.swing.JLabel();
        adm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pd = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpwd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/loginb.jpg"))); // NOI18N
        lg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgMouseClicked(evt);
            }
        });
        panel_print.add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 231, 140, 30));

        adm.setBorder(null);
        adm.setOpaque(false);
        panel_print.add(adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 110, 20));

        jLabel2.setText(" ");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        panel_print.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 230, 40));

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panel_print.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 70, 20));

        pd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/passwordb.jpg"))); // NOI18N
        pd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdMouseClicked(evt);
            }
        });
        panel_print.add(pd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 110, 20));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("Terms & Conditions");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_print.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 130, 20));

        jpwd.setBorder(null);
        panel_print.add(jpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 160, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        panel_print.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, 30));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        panel_print.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 100, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/new login.jpg"))); // NOI18N
        panel_print.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, -1));

        getContentPane().add(panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 630));

        setSize(new java.awt.Dimension(358, 643));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdMouseClicked
         pd.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_pdMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
try{
        Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://remotemysql.com:3306/PwgAV9gxe3","PwgAV9gxe3","CjiamOUePn");
        Statement stmt=con.createStatement();
        int a=Integer.parseInt(adm.getText());
        String pwd=new String(jpwd.getPassword());
        stmt.executeUpdate("delete from currnt_user;");
        stmt.executeUpdate("insert into currnt_user values('"+a+"');");
        String q="select*from sdetail where admno='"+a+"'";
        ResultSet rs=stmt.executeQuery(q);  
        rs.next();
        String s1=rs.getString("password");
        if(pwd.equals(s1)){
          new loading().setVisible(true);
          this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null,"Incorrect Password");
        }                
        
        stmt.close();
        con.close();                      
}
catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            }  
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgMouseClicked
       lg.setVisible(false);
    }//GEN-LAST:event_lgMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
new signup().setVisible(true);
this.dispose();      
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new forget().setVisible(true);
this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jpwd;
    private javax.swing.JLabel lg;
    private javax.swing.JPanel panel_print;
    private javax.swing.JLabel pd;
    // End of variables declaration//GEN-END:variables
}
