import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JiTU-PC
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jname = new javax.swing.JLabel();
        jfather = new javax.swing.JLabel();
        jadm = new javax.swing.JLabel();
        jtution = new javax.swing.JLabel();
        jstat = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        done = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        jbus = new javax.swing.JLabel();
        _________jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/iconfinder_arrow-right_227601.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 20));

        jLabel2.setFont(new java.awt.Font("Simplified Arabic", 3, 14)); // NOI18N
        jLabel2.setText("Admission No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 100, 20));

        jname.setFont(new java.awt.Font("Simplified Arabic", 3, 14)); // NOI18N
        getContentPane().add(jname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 120, 20));

        jfather.setFont(new java.awt.Font("Simplified Arabic", 3, 14)); // NOI18N
        getContentPane().add(jfather, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 100, 20));

        jadm.setFont(new java.awt.Font("Simplified Arabic", 3, 14)); // NOI18N
        getContentPane().add(jadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 100, 20));

        jtution.setFont(new java.awt.Font("Simplified Arabic", 3, 14)); // NOI18N
        getContentPane().add(jtution, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 100, 20));

        jstat.setFont(new java.awt.Font("Simplified Arabic", 3, 14)); // NOI18N
        getContentPane().add(jstat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 80, 20));

        jLabel7.setFont(new java.awt.Font("Simplified Arabic", 3, 14)); // NOI18N
        jLabel7.setText("Name ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 40, 20));

        jLabel8.setFont(new java.awt.Font("Simplified Arabic", 3, 14)); // NOI18N
        jLabel8.setText("Bus Fee ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 100, 20));

        jLabel9.setFont(new java.awt.Font("Simplified Arabic", 3, 14)); // NOI18N
        jLabel9.setText("Father's Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 100, 20));

        jLabel10.setFont(new java.awt.Font("Simplified Arabic", 3, 14)); // NOI18N
        jLabel10.setText("Tuition Fee");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 100, 20));

        jLabel12.setFont(new java.awt.Font("Simplified Arabic", 3, 14)); // NOI18N
        jLabel12.setText("Payment Status:");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 110, 20));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 40, 40));

        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 50, 40));

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 40, 40));

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 40, 40));

        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 40, 40));

        done.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/giphy.gif"))); // NOI18N
        getContentPane().add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 160, 80));

        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/error.gif"))); // NOI18N
        getContentPane().add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 160, 80));

        jbus.setFont(new java.awt.Font("Simplified Arabic", 3, 14)); // NOI18N
        getContentPane().add(jbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 100, 20));

        _________jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/payment.jpg"))); // NOI18N
        getContentPane().add(_________jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        setSize(new java.awt.Dimension(287, 632));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
new Main().setVisible(true);
this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         try{
        Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://remotemysql.com:3306/PwgAV9gxe3","PwgAV9gxe3","CjiamOUePn");
        Statement stmt=con.createStatement();
        
       
       
        ResultSet rs=stmt.executeQuery("select*from currnt_user");  
        rs.next();
        String s1=rs.getString("admno");
        String q="select*from sdetail where admno='"+s1+"'";
        ResultSet js=stmt.executeQuery(q);
        js.next();
        String s2=js.getString("name");  
        String s3=js.getString("father");
        
           jname.setText(s2);
           jfather.setText(s3);
           jadm.setText(s1);
        String a="select*from payment where admno='"+s1+"'";
        ResultSet ps=stmt.executeQuery(a);
        ps.next();   
        String s4=ps.getString("tution_fee");  
        String s5=ps.getString("bus_fee");
        String s6=ps.getString("status");
           jtution.setText(s4); 
           jbus.setText(s5);
           jstat.setText(s6);
           if(s6.equals("done")){
           done.setVisible(true);
           error.setVisible(false);
           }
           else{
               error.setVisible(true);
           done.setVisible(false);
           }
           
      rs.close();
      js.close();
      ps.close();  
        stmt.close();
      con.close();                      
}
catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            }   
    }//GEN-LAST:event_formWindowOpened

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
new Main().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
new feedback().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
new Profile().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
new settings().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
new notification().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _________jLabel3;
    private javax.swing.JLabel done;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jadm;
    private javax.swing.JLabel jbus;
    private javax.swing.JLabel jfather;
    private javax.swing.JLabel jname;
    private javax.swing.JLabel jstat;
    private javax.swing.JLabel jtution;
    // End of variables declaration//GEN-END:variables
}
