
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Deepesh
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdob = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jstudent = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email_1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jphone = new javax.swing.JTextField();
        email_ = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        phone_ = new javax.swing.JLabel();
        phone_1 = new javax.swing.JLabel();
        jfather = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        notic = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        prof = new javax.swing.JLabel();
        setting = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdob.setEditable(false);
        jdob.setBackground(new java.awt.Color(232, 236, 239));
        jdob.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jdob.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jdob.setBorder(null);
        jdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdobActionPerformed(evt);
            }
        });
        getContentPane().add(jdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 210, 20));

        jemail.setEditable(false);
        jemail.setBackground(new java.awt.Color(232, 236, 239));
        jemail.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jemail.setBorder(null);
        jemail.setOpaque(false);
        jemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemailActionPerformed(evt);
            }
        });
        getContentPane().add(jemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 210, 30));

        jstudent.setEditable(false);
        jstudent.setBackground(new java.awt.Color(232, 236, 239));
        jstudent.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jstudent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jstudent.setBorder(null);
        jstudent.setOpaque(false);
        getContentPane().add(jstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 260, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 260, 10));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/icons8-feedback-32s.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/edit_query.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 40, 30));

        email_1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        email_1.setForeground(new java.awt.Color(102, 102, 102));
        email_1.setText("Date Of Birth");
        getContentPane().add(email_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 110, 30));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 260, 10));

        jphone.setEditable(false);
        jphone.setBackground(new java.awt.Color(232, 236, 239));
        jphone.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jphone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jphone.setBorder(null);
        jphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jphoneActionPerformed(evt);
            }
        });
        getContentPane().add(jphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 210, 30));

        email_.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        email_.setForeground(new java.awt.Color(102, 102, 102));
        email_.setText("E-mail");
        getContentPane().add(email_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 80, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/edit_query.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 40, 30));

        phone_.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        phone_.setForeground(new java.awt.Color(102, 102, 102));
        phone_.setText("Phone");
        getContentPane().add(phone_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 396, 80, 30));

        phone_1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        phone_1.setForeground(new java.awt.Color(102, 102, 102));
        phone_1.setText("Father's Name");
        getContentPane().add(phone_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 130, 30));

        jfather.setEditable(false);
        jfather.setBackground(new java.awt.Color(232, 236, 239));
        jfather.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jfather.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfather.setBorder(null);
        jfather.setOpaque(false);
        getContentPane().add(jfather, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 210, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 260, 10));

        notic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noticMouseClicked(evt);
            }
        });
        getContentPane().add(notic, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/iconfinder_arrow-right_227601.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));

        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 40, 30));

        prof.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prof.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profMouseClicked(evt);
            }
        });
        getContentPane().add(prof, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 50, 40));

        setting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingMouseClicked(evt);
            }
        });
        getContentPane().add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 40, 50));

        jLabel3.setBackground(new java.awt.Color(232, 236, 239));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/icons8-user-64.png"))); // NOI18N
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 170, 110));

        jLabel1.setBackground(new java.awt.Color(83, 107, 124));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/profilefinal.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 630));

        setSize(new java.awt.Dimension(295, 632));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
new Main().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homeMouseClicked

    private void profMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profMouseClicked
new Profile().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_profMouseClicked

    private void settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseClicked
new settings().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_settingMouseClicked

    private void noticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noticMouseClicked
new notification().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_noticMouseClicked

    private void jdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdobActionPerformed

    private void jemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemailActionPerformed
try{
        Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://remotemysql.com:3306/PwgAV9gxe3","PwgAV9gxe3","CjiamOUePn");
        Statement stmt=con.createStatement();
        
       
       
        ResultSet rs=stmt.executeQuery("select*from currnt_user");  
        rs.next();
        String s1=rs.getString("admno");
        String s=jemail.getText();
        String q="update sdetail set email='"+s+"' where admno='"+s1+"'";
        stmt.executeUpdate(q);
       
       
      rs.close();
      stmt.close();
      con.close();                      
}
catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jemailActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
     new feedback().setVisible(true);
this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try{
        Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://remotemysql.com:3306/PwgAV9gxe3","PwgAV9gxe3","CjiamOUePn");
        Statement stmt=con.createStatement();
        
       
       
        ResultSet rs=stmt.executeQuery("select*from currnt_user");  
        rs.next();
        String s1=rs.getString("admno");
        String q="select*from sdetail where admno='"+s1+"'";
        ResultSet js=stmt.executeQuery(q);
        js.next();
        String s2=js.getString("name");  
        String s3=js.getString("father");
        String s4=js.getString("phone");
        String s5=js.getString("email");
        String s6=js.getString("dob");
           jstudent.setText(s2);
           jfather.setText(s3);
           jphone.setText(s4);
           jemail.setText(s5);
           jdob.setText(s6);
           
      rs.close();
      js.close();
      stmt.close();
      con.close();                      
}
catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            }    
    }//GEN-LAST:event_formWindowOpened

    private void jphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jphoneActionPerformed
         try{
        Class.forName("java.sql.Driver");
      Connection con=DriverManager.getConnection("jdbc:mysql://remotemysql.com:3306/PwgAV9gxe3","PwgAV9gxe3","CjiamOUePn");
        Statement stmt=con.createStatement();
        
       
       
        ResultSet rs=stmt.executeQuery("select*from currnt_user");  
        rs.next();
        String s1=rs.getString("admno");
        int s=Integer.parseInt(jphone.getText());
        String q="update sdetail set phone='"+s+"' where admno='"+s1+"'";
        stmt.executeUpdate(q);
       
       
      rs.close();
      stmt.close();
      con.close();                      
}
catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            }    
    }//GEN-LAST:event_jphoneActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       jphone.setEditable(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       jemail.setEditable(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel email_;
    private javax.swing.JLabel email_1;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jdob;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jfather;
    private javax.swing.JTextField jphone;
    private javax.swing.JTextField jstudent;
    private javax.swing.JLabel notic;
    private javax.swing.JLabel phone_;
    private javax.swing.JLabel phone_1;
    private javax.swing.JLabel prof;
    private javax.swing.JLabel setting;
    // End of variables declaration//GEN-END:variables
}
