
import java.sql.Connection;
import java.sql.DriverManager;

import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JiTU-PC
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jname = new javax.swing.JLabel();
        jadm = new javax.swing.JLabel();
        jfather = new javax.swing.JLabel();
        jemail = new javax.swing.JLabel();
        jphone = new javax.swing.JLabel();
        jdob = new javax.swing.JLabel();
        jpwd = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        tadm = new javax.swing.JTextField();
        tfather = new javax.swing.JTextField();
        temail = new javax.swing.JTextField();
        tphone = new javax.swing.JTextField();
        tdob = new javax.swing.JTextField();
        tpwd = new javax.swing.JTextField();
        click = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jname.setBackground(new java.awt.Color(255, 255, 255));
        jname.setFont(new java.awt.Font("Raavi", 0, 12)); // NOI18N
        jname.setText("Student Name");
        jname.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jnameMouseClicked(evt);
            }
        });
        getContentPane().add(jname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 160, 20));

        jadm.setFont(new java.awt.Font("Raavi", 0, 12)); // NOI18N
        jadm.setText("Admissin No.");
        jadm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jadm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jadmMouseClicked(evt);
            }
        });
        getContentPane().add(jadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 160, 20));

        jfather.setFont(new java.awt.Font("Raavi", 0, 12)); // NOI18N
        jfather.setText("Father's Name");
        jfather.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jfather.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jfatherMouseClicked(evt);
            }
        });
        getContentPane().add(jfather, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 160, 30));

        jemail.setFont(new java.awt.Font("Raavi", 0, 12)); // NOI18N
        jemail.setText("Email Id");
        jemail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jemailMouseClicked(evt);
            }
        });
        getContentPane().add(jemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 160, 30));

        jphone.setFont(new java.awt.Font("Raavi", 0, 12)); // NOI18N
        jphone.setText("Phone Number");
        jphone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jphone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jphoneMouseClicked(evt);
            }
        });
        getContentPane().add(jphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 368, 160, -1));

        jdob.setFont(new java.awt.Font("Raavi", 0, 12)); // NOI18N
        jdob.setText("Date of birth");
        jdob.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jdob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdobMouseClicked(evt);
            }
        });
        getContentPane().add(jdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 160, 30));

        jpwd.setFont(new java.awt.Font("Raavi", 0, 12)); // NOI18N
        jpwd.setText("Password");
        jpwd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpwdMouseClicked(evt);
            }
        });
        getContentPane().add(jpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 160, 20));

        tname.setBorder(null);
        getContentPane().add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 170, 20));

        tadm.setBorder(null);
        getContentPane().add(tadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 180, 20));

        tfather.setBorder(null);
        getContentPane().add(tfather, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 150, 20));

        temail.setBorder(null);
        getContentPane().add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 150, 20));

        tphone.setBorder(null);
        getContentPane().add(tphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 364, 150, 20));

        tdob.setBorder(null);
        getContentPane().add(tdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 404, 150, 20));

        tpwd.setBorder(null);
        getContentPane().add(tpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 140, 30));

        click.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickMouseClicked(evt);
            }
        });
        getContentPane().add(click, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/iconfinder_arrow-right_227601.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/signup_1.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 640));

        setSize(new java.awt.Dimension(348, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jnameMouseClicked
        jname.setVisible(false);
    }//GEN-LAST:event_jnameMouseClicked

    private void jfatherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jfatherMouseClicked
       jfather.setVisible(false);
    }//GEN-LAST:event_jfatherMouseClicked

    private void jemailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jemailMouseClicked
       jemail.setVisible(false);
    }//GEN-LAST:event_jemailMouseClicked

    private void jphoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jphoneMouseClicked
jphone.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jphoneMouseClicked

    private void jdobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdobMouseClicked
jdob.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jdobMouseClicked

    private void jpwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpwdMouseClicked
jpwd.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jpwdMouseClicked

    private void jadmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadmMouseClicked
        jadm.setVisible(false);
    }//GEN-LAST:event_jadmMouseClicked

    private void clickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickMouseClicked
       try{
        Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://remotemysql.com:3306/PwgAV9gxe3","PwgAV9gxe3","CjiamOUePn");
        Statement stmt=con.createStatement();
        String s1=tname.getText();
        int s2=Integer.parseInt(tadm.getText());
        
        
        String s3=tfather.getText();
        String s4=temail.getText();
        String s5=tphone.getText();
        String s6=tdob.getText();
        String s7=tpwd.getText();
        
       stmt.executeUpdate("insert into sdetail values('"+s2+"','"+s1+"','"+s3+"','"+s5+"','"+s4+"','"+s6+"','"+s7+"');");
       
       JOptionPane.showMessageDialog(null,"Sign up succesfully"); 
        
        stmt.close();
        con.close();                      
}
catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            }  
    }//GEN-LAST:event_clickMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new newlogin().setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel click;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jadm;
    private javax.swing.JLabel jdob;
    private javax.swing.JLabel jemail;
    private javax.swing.JLabel jfather;
    private javax.swing.JLabel jname;
    private javax.swing.JLabel jphone;
    private javax.swing.JLabel jpwd;
    private javax.swing.JTextField tadm;
    private javax.swing.JTextField tdob;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tfather;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tphone;
    private javax.swing.JTextField tpwd;
    // End of variables declaration//GEN-END:variables
}
